-- LINGGUANG Health OS cloud core
-- First-stage sync model: one encrypted-at-rest JSON document per authenticated user.
-- Apply to a dedicated LINGGUANG Supabase project, not the existing RUNLU warehouse project.

create table if not exists public.lingguang_user_store (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{"patients":[],"appointments":[],"intakes":[],"clinicalNotes":[],"checkins":[],"followups":[],"riskReviews":[],"applications":[],"messages":[],"voiceSessions":[]}'::jsonb,
  version integer not null default 1,
  updated_at timestamptz not null default now()
);

alter table public.lingguang_user_store enable row level security;

create policy "lingguang users read own store"
on public.lingguang_user_store
for select
to authenticated
using (auth.uid() = user_id);

create policy "lingguang users insert own store"
on public.lingguang_user_store
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "lingguang users update own store"
on public.lingguang_user_store
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.lingguang_ai_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  task text not null check (task in ('voice','scan')),
  status text not null,
  latency_ms integer,
  created_at timestamptz not null default now()
);

alter table public.lingguang_ai_usage enable row level security;

create policy "lingguang users read own ai usage"
on public.lingguang_ai_usage
for select
to authenticated
using (auth.uid() = user_id);

create policy "lingguang users insert own ai usage"
on public.lingguang_ai_usage
for insert
to authenticated
with check (auth.uid() = user_id);
